<?php

namespace Jac\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getPrivileges($user) {
        $query = $this->createQueryBuilder('u')
            ->join('u.privileges', 'p')
            ->join('p.sousMenu', 's')
            ->join('s.menu', 'm')
            ->addSelect( 'm', 's', 'p')
            ->where('p.user = :user')
           // ->groupBy('m')
            ->setParameter('user', $user)
            ->getQuery()
            ->getArrayResult();
        return $query;

    }
    
    public function getMenus($user) {
        $em = $this->getEntityManager();
        $query = $em->createQuery( //creation de la requête
            'SELECT DISTINCT m
            FROM AppBundle:Menu m, AppBundle:SousMenu s, AppBundle:Privilege p
            WHERE p.sousMenu = s.id 
            AND s.menu = m.id
            AND p.user = :param
            ORDER BY m.id ASC'
        )->setParameter('param', $user);

        return $query->getResult(); //variable qui récupère la requête
    }
    
    public function getSousMenus($user) {
        $em = $this->getEntityManager(); //on appelle Doctrine
        $query = $em->createQuery( //creation de la requête
            'SELECT DISTINCT s
            FROM AppBundle:SousMenu s, AppBundle:Privilege p
            WHERE p.sousMenu = s.id 
            AND p.user = :param
            ORDER BY s.id ASC'
        )->setParameter('param', $user);

        return $query->getResult(); //variable qui récupère la requête
    }
}