<?php

namespace AppBundle\Repository;

/**
 * AssignationBeneficiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignationBeneficiaireRepository extends \Doctrine\ORM\EntityRepository
{
}
