<?php

namespace AppBundle\Repository;

/**
 * CoffrefortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoffrefortRepository extends \Doctrine\ORM\EntityRepository {

}
