<?php

namespace AppBundle\Repository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptebancaireRepository extends \Doctrine\ORM\EntityRepository
{
}
