<?php

namespace AppBundle\Repository;

/**
 * EncaissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncaissementRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getEncaissement($exo) {
//        $qb = $this->createQueryBuilder('e')
//            ->leftJoin('e.appel', 'a')
//            ->addSelect('a')
//            ->where('a.estAnnuler = 0')
//            ->andWhere('a.estParentannuler = 0')
//            ->andWhere('a.exercice =:exo')
//            ->setParameter('exo', $exo)
//            ->orderBy('e.dateEncaissement', 'ASC');
//        return $qb->getQuery()
//            ->getResult();
//    }
}
