<?php

namespace AppBundle\Repository;

/**
 * PrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivilegeRepository extends \Doctrine\ORM\EntityRepository
{
}
