<?php

namespace AppBundle\Repository;

/**
 * RetenuePaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetenuePaieRepository extends \Doctrine\ORM\EntityRepository
{
}
